export const MSG_ADD_TO_CART_SUCCESS ='ADD SUCCESS';
export const MSG_UPDATE_TO_CART_SUCCESS ='UPDATE SUCCESS';
export const MSG_DELETE_TO_CART_SUCCESS ='DELETE SUCCESS';
export const MSG_CART_EMPTY = 'CART EMPTY0';
export const MSG_WELLCOME = 'WELLCOME SHOPPING';